spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: root
    password: root
    driverClassName: org.postgresql.Driver

#第一字母后的xxx避免aliyun的检测
#oss:
#  accessKeyId: L xxx TAI5tBsifGw4kdE8VupdX2V
#  accessKeySecret: Y xxx xRqKhAb9Ri9UA3WCA7DRBSpAcaljD
#  endpoint: o xxx ss-cn-beijing.aliyuncs.com
#  bucket: e xxx ric-cource

oss:
  accessKeyId: xxx
  accessKeySecret: xxx
  endpoint: xxx
  bucket: xxx

#第一字母后的xxx避免aliyun的检测
#alipay:
#  gatewayUrl: h xxx ttps://openapi.alipaydev.com/gateway.do
#  appId: 2 xxx 021000118602867
#  merchantPrivateKey: M xxx IIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDNERe1AbfnBKTLsRD34CVDxzIiUpx1UBSeOTqQljaapXf+5hYNqUkLmy6Ckz823eozyFT9kbZUTjdmChuZahndtLAgOgzrHHnOYlbNf0ue0391lXPVwHbpGC90fG4FdAx04ZNWUVeIjJ3+CWUA1Z+kEVE9/MXiZiZ05PDULpz1GWivHCBoYC4+pP25EQngFTXtONtvhrZgV2eGJ9Og/GERM59Ni1LJO2JAVfiz4iQ34s3Q7NJewuwyymGFCSHsKcBINMzenmnkE2KSCQJ3aGoQ0kbtTritZALtO/Ys98jcGFRqhaTjp81GScenXpFADimJboizd4W0eFBwgS1Q+DipAgMBAAECggEABa0RcOspQfW48gJmq9XCckvTMWwD9KNQzshavKHLxSALYDzSI3KqGO4krWyR9VzTHLfQ0mv0FgVMN0DUXry3FpHnxhyVOvTA0luad3msiCrmfkSyvhnjsLQArEK9cN0zcxDDWUJLH/Z0cRGlgA5pqsrn6sVSXN/i9J1ZpSXdJlOPAP3sINpDCIxcr2W1sb2CBf1q+IlNthupghcnQcEq9OovvXh3B81Lvtg0Z6kRRXVL8tT0ivxrn7GeZZfvsHqjwCfFLU0wUsTTMnkwLVGgqMVn66eJFoFI7/p5m/U3iHEbQqkM76IGSCqihFqFtylRtXl1v6UEcZZLtdaAWHIZOQKBgQD17g6mtNaA1bJyi1lMSL3wm7iDS8118+xoqFFC1u/v7TlyAfwjFSEtWx5VfQuOX+TJR0qOsPH0HIBncMw6ov5q3+AXbT9fdzw6QUQ3pthD95jiCL33mnLPi6yjsE6oWEEfGpOyoqXHDwpqK+vyTjsk9bslBMf2v1BNPyd0TYN4VwKBgQDVdrC9VO3kVY68Uus89pJLUQQE4eu9QrvF4xuGyEuQvaRH3/5SYev7S/aLPfgKnuXT+P6l6PPhxfRxTKQGjo5e5E5PrpFVgmleCrdvS1553soXH+ofVulgXNgzYOI2lB7xCnfKE/6mOWBKttsLFzeoc6RB8Fd79i5SNCSiTMc2/wKBgQDRKZ4mZOmG+7lguGnDep6pFBgS+xaM+l+YB4fNfDbnbXCNKWkDgYYNKFEdTlPUzHQuSEb+Izo1b0Q6NfJM8LHHvg6+ffkHPcbomPfnCS0oaV4K6HqBK0f4gwfa1Cmh/iWsyZLSvIiYS4+FC0QKekTNQ33elzlnAAHRISRyQzbM0wKBgBwEmiofraHcwQFi+NFlo8oS9i4V4TVUPwU4S/Ki85gp7BgrBFyX0buIOvIHzjjGpm/uLK5mJyypKO5+GsFpkLJP0R+QUC8jEOVxDqajA+GHJotmevpmE/e79/y2aLq1MmJ890Ak47W5rjPgUFviTkHj+9lTzIfOxkGv6mcLINLNAoGBANn2m5V/9JHUpndoqRVwOXh+ZuYYRI5XrzRM0xbpM5gmWDDEapdP5ibX7BrPL4Ue7pj3NkdWlGlGpauL1Nm1uYHlfUTMkHMULeaHBRiVcWs/iUWI0rNV8uSQpja+7GhHO8MNJrU90gDspRxMd7no2jyxh6Q9uL5PatWEBOFDnOxY
#  alipayPublicKey: M xxx IIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkifo4oiaU1/uEZRDn9o/E8Ev5Ltuha27A9JWfvCHJ+x/qjIi8th7FjN5lx89q3gYDYKsI3F8nlrr47ZJZBKzElURX2RBt96F/G1K0pV0d0me+rythv4a8+5s7wWyuRtxG8AkTrRxrnndcIP8HH3AOZ+FywVhVmJO/9NUxK5OCjK3acqdHkgDBAipzSQ0bxv3D1oGBrpT3qpLfvKOdXxvogxi6DRIZlljic/gYwBleWqq82TOJxYdXMH3LWiaLAwSNflCJmL3IxgkPKZoDDny3gRsf1RtvpmgdQww0onGLXAxFUt/3ff4PgFHQa1JGY7n2BdxtuTZJcj4y3TzgYA7hQIDAQAB

alipay:
  gatewayUrl: xxx
  appId: xxx
  merchantPrivateKey: xxx
  alipayPublicKey: xxx
